# Application name
spring.application.name=base

# Server Configuration
server.port=8083

# Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA & Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable CORS
spring.web.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:3000}
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE
spring.web.cors.allowed-headers=*

# OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=579266292777-5ib39aoa2gpe8bfbgkn15amsikls2ram.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8083/login/oauth2/code/google

# OAuth2 Provider Configuration
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=name

# Profile configuration
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Logging
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.oauth2=TRACE
