package com.example.base.model;

import jakarta.persistence.*;
/**
 * Recipe represents an entity that maps to the "recipes" table in the database.
 * It corresponds to the schema:
 *   CREATE TABLE recipes (
 *     recipe_id INT AUTO_INCREMENT PRIMARY KEY,
 *     name VARCHAR(255) NOT NULL,
 *     description TEXT,
 *     category_id INT NOT NULL
 *   );
 */
/**
 * Recipe represents a recipe entity that maps to the "recipes" table in the database.
 * Each instance of this class corresponds to a record in the table, containing information
 * such as the recipe name, description, and its associated category.
 */
@Entity  // Specifies that this class is an entity to be managed by JPA.
@Table(name = "recipes")  // Maps this entity to the "recipes" table.
public class Recipe {

    /**
     * The unique identifier for the recipe.
     * It is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long recipeId;  // Alternatively, you can name this "recipe_id" if preferred.

    /**
     * The name of the recipe.
     * This field is required (cannot be null).
     */
    @Column(nullable = false)
    private String name;

    /**
     * A detailed description of the recipe.
     * This is stored as a TEXT column in the database.
     */
    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * The category identifier to which the recipe belongs.
     * This is also a required field.
     */
    @Column(nullable = false)
    private int categoryId;

    // Constructors, getters, and setters
    // You can generate these methods automatically using your IDE.

    // Example constructor:
    public Recipe() {}

    public Recipe(String name, String description, int categoryId) {
        this.name = name;
        this.description = description;
        this.categoryId = categoryId;
    }

    // Getters and setters
    public Long getRecipeId() {
        return recipeId;
    }

    public void setRecipeId(Long recipeId) {
        this.recipeId = recipeId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }
}
