# application-dev.properties (Development Settings for H2)

#server.port=8081
# H2 Database Configuration for Local Testing
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA & Hibernate Configuration for H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



#  This file is meant for local development. \
#  It configures application to use an \
#  in-memory H2 database, which is simple to \
#  set up and requires no external database server. \
#  Since data in H2 is temporary (it?s stored in memory), \
#  it?s ideal for development and testing.