# Application name
spring.application.name=base

# Database Configuration
spring.datasource.url=jdbc:mysql://mysql-container:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=5

# JPA & Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port (Heroku will override this with PORT environment variable)
server.port=8082

# Enable CORS
spring.web.cors.allowed-origins=${ALLOWED_ORIGINS:*}
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE
spring.web.cors.allowed-headers=*

# Profile configuration
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=579266292777-5ib39aoa2gpe8bfbgkn15amsikls2ram.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8082/login/oauth2/code/google
spring.security.oauth2.client.registration.google.client-name=Google

# Static Resource Configuration
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**
spring.web.resources.cache.period=0
